# Generated by Django 4.0.5 on 2022-06-21 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publication_date',
            field=models.DateField(default=datetime.date(2022, 6, 21)),
        ),
    ]
