# Generated by Django 4.0.5 on 2022-07-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_isbn_books_added_by_books_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='image_url',
            new_name='book_cover',
        ),
    ]
