# Generated by Django 4.0.5 on 2022-07-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_image_url_books_book_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
