# Generated by Django 4.0.5 on 2022-07-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='Date_added',
        ),
    ]
