# Generated by Django 4.0.5 on 2022-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_publication_date_book_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='borrowed_book',
            name='fine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowed_book',
            name='return_status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('TAKEN', 'Taken'), ('RETURNED', 'Returned')], default='BOOKED', max_length=15),
        ),
    ]
