# Generated by Django 4.0.5 on 2022-08-08 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_remove_borrowed_book_date_returned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed_book',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='borrowed_book',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='borrowed_book',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='borrowed_book',
            name='return_status',
            field=models.CharField(choices=[('BOOKED', 'Booked')], default='BOOKED', max_length=15),
        ),
        migrations.CreateModel(
            name='Issued_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(null=True)),
                ('pickup_date', models.DateTimeField(null=True)),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('BOOKED', 'Booked'), ('TAKEN', 'Taken'), ('RETURNED', 'Returned')], default='BOOKED', max_length=15)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.borrowed_book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
