# Generated by Django 4.0.5 on 2022-08-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rename_return_status_borrowed_book_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued_book',
            name='date_returned',
            field=models.DateTimeField(null=True),
        ),
    ]
